# -*- coding: utf-8 -*-
"""accident data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8EwuJ7_fVd05wh7crgLkLbsibb3s3k3
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_squared_error, r2_score

import os

os.listdir(path)

!pip install kagglehub

import kagglehub

path = kagglehub.dataset_download("tsiaras/uk-road-safety-accidents-and-vehicles")

print("Dataset path:", path)

import os

os.listdir(path)

df = pd.read_csv(path + "/Accident_Information.csv")

df.head()

for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

import pandas as pd

df = pd.read_csv("/kaggle/input/uk-road-safety-accidents-and-vehicles/Accident_Information.csv")

df.head()

df.shape

df.columns

df.info()

df = df.dropna()

y = df['Number_of_Casualties']

X = df[['Weather_Conditions','Light_Conditions','Road_Type','Speed_limit']]

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in X.select_dtypes(include=['object']).columns:
    X[col] = le.fit_transform(X[col])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Casualties")

plt.ylabel("Predicted Casualties")

plt.title("Actual vs Predicted Casualties")

plt.show()